version: '3'
services:
  docusaurus:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run start -- --host 0.0.0.0
